// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezlxtwaptyrwagsdvykc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6bHh0d2FwdHlyd2Fnc2R2eWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODI3OTIsImV4cCI6MjA2MDA1ODc5Mn0.YjWz-6VkyfqYO59pF1tHWFVGr1RGMU50r2kIofZzFOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);